package com.esgi.mymusic.domain

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue

@Parcelize
data class ArtistDetail(
    val idArtist: String?,
    val idLabel: String?,
    val intBornYear: String?,
    val intCharted: String?,
    val intDiedYear: @RawValue Any?,
    val intFormedYear: String?,
    val intMembers: String?,
    val strArtist: String?,
    val strArtistAlternate: String?,
    val strArtistBanner: String?,
    val strArtistClearart: String?,
    val strArtistCutout: String?,
    val strArtistFanart: String?,
    val strArtistFanart2: String?,
    val strArtistFanart3: String?,
    val strArtistFanart4: String?,
    val strArtistLogo: String?,
    val strArtistStripped: @RawValue Any?,
    val strArtistThumb: String?,
    val strArtistWideThumb: String?,
    val strBiographyCN: @RawValue Any?,
    val strBiographyDE: String?,
    val strBiographyEN: String?,
    val strBiographyES: String?,
    val strBiographyFR: String?,
    val strBiographyHU: @RawValue Any?,
    val strBiographyIL: @RawValue Any?,
    val strBiographyIT: String?,
    val strBiographyJP: @RawValue Any?,
    val strBiographyNL: @RawValue Any?,
    val strBiographyNO: @RawValue Any?,
    val strBiographyPL: @RawValue Any?,
    val strBiographyPT: @RawValue Any?,
    val strBiographyRU: @RawValue Any?,
    val strBiographySE: @RawValue Any?,
    val strCountry: String?,
    val strCountryCode: String?,
    val strDisbanded: @RawValue Any?,
    val strFacebook: String?,
    val strGender: String?,
    val strGenre: String?,
    val strISNIcode: @RawValue Any?,
    val strLabel: String?,
    val strLastFMChart: String?,
    val strLocked: String?,
    val strMood: String?,
    val strMusicBrainzID: String?,
    val strStyle: String?,
    val strTwitter: String?,
    val strWebsite: String?
) : Parcelable